services:
  backend:
    image: sortify-backend
    container_name: sortify-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9876:9876"
    
    # Set the active profile to docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker


# frontend:    
#    # Make sure network exists for connection to frontend
#     networks:
#       - sortify-network

# # Define the Docker network
# networks:
#   - sortify-network
