name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        gradle-version: '7.4'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Run tests (placeholder)
      run: echo "Run tests here"  # Placeholder, actual test step will be added later
